---
- name: Deploy Docker container
  hosts: app_servers  
  become: yes
  vars:
    docker_image: "{{ image_name }}"  
    container_name: "spring-petclinic"

  tasks:
    - name: Pull the latest Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull
      register: pulled_image

    - name: Stop and remove existing container if it exists
      docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes

    - name: Start the new container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        ports:
          - "80:8080"  
        env:
          DB_NAME: "{{ DB_NAME }}"
          DB_HOST: "{{ DB_HOST }}"  
          DB_PORT: "{{ db_port }}"
          DB_USERNAME: "{{ POSTGRES_USER }}"
          DB_PASSWORD: "{{ POSTGRES_PASS }}"
          SPRING_PROFILES_ACTIVE: "{{ SPRING_PROFILES_ACTIVE }}"
          spring_datasource_url: jdbc:postgresql://ilynch-db.cma1xp5df2gi.us-east-1.rds.amazonaws.com:5432/springAppDB
          spring_datasource_username: "{{ POSTGRES_USER }}"
          spring_datasource_password: "{{ POSTGRES_PASS }}"

    - name: Print application URL
      debug:
        msg: "Application deployed at http://{{ inventory_hostname }}:80"
