---
- name: Deploy Docker container
  hosts: app_servers  
  become: yes
  vars:
    docker_image: "{{ image_name }}"  
    container_name: "spring-petclinic"

  tasks:
    - name: Pull the latest Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull
      register: pulled_image

    - name: Stop and remove existing container if it exists
      docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes

    - name: Start the new container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        ports:
          - "80:8080"  
        env:
          DB_HOST: "{{ DB_HOST }}"  
          DB_PORT: "{{ db_port }}"
          DB_USERNAME: "{{ POSTGRES_USER }}"
          DB_PASSWORD: "{{ POSTGRES_PASS }}"
          SPRING_PROFILES_ACTIVE: "{{ SPRING_PROFILES_ACTIVE }}"

    - name: Print application URL
      debug:
        msg: "Application deployed at http://{{ inventory_hostname }}:80"
