---
- name: Check and install Docker and Docker Compose
  hosts: all  # Specify your target hosts here
  become: yes
  tasks:

    - name: Check if Docker is already installed
      ansible.builtin.command: docker --version
      register: docker_installed
      ignore_errors: yes

    - name: Install Docker prerequisites on Debian-based systems
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      when:
        - ansible_os_family == "Debian"
        - docker_installed.failed  # Run only if Docker is not installed

    - name: Add Docker GPG key on Debian-based systems
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when:
        - ansible_os_family == "Debian"
        - docker_installed.failed

    - name: Add Docker repository on Debian-based systems
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when:
        - ansible_os_family == "Debian"
        - docker_installed.failed

    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes
      when:
        - ansible_os_family == "Debian"
        - docker_installed.failed

    - name: Install Docker on Debian-based systems
      ansible.builtin.apt:
        name: docker-ce
        state: present
      when:
        - ansible_os_family == "Debian"
        - docker_installed.failed

    - name: Install Docker dependencies on RedHat-based systems
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
      when:
        - ansible_os_family == "RedHat"
        - docker_installed.failed

    - name: Add Docker repository on RedHat-based systems
      ansible.builtin.command:
        cmd: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
      when:
        - ansible_os_family == "RedHat"
        - docker_installed.failed

    - name: Install Docker on RedHat-based systems
      ansible.builtin.yum:
        name: docker-ce
        state: present
      when:
        - ansible_os_family == "RedHat"
        - docker_installed.failed

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
      when: docker_installed.failed  # Only if Docker was not previously installed

    - name: Install Docker Compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system | lower }}-{{ ansible_machine }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verify Docker installation
      ansible.builtin.command: docker --version
      when: docker_installed.failed  # Only if Docker was installed by this playbook

    - name: Verify Docker Compose installation
      ansible.builtin.command: docker-compose --version
