---
- name: Configure Jenkins environment for semver
  hosts: jenkins_slaves
  become: yes
  tasks:
    - name: Ensure pip is installed
      package:
        name: python3-pip
        state: present

    - name: Install semver globally
      pip:
        name: semver
        state: present
        executable: pip3

    - name: Ensure Jenkins user has semver in PATH
      lineinfile:
        path: /etc/profile.d/jenkins.sh
        line: 'export PATH=$PATH:~/.local/bin'
        create: yes
      notify: Reload environment

  handlers:
    - name: Reload environment
      shell: source /etc/profile
      become: yes
